language: node_js
node_js:
      - "10.3.0"
install:
     - npm install
script:
     - npm run test
after_success:
      - npm run test:cov
notifications:
  email:
    - adrien.deperetti.freelance@gmail.com